title: blog
email: john.lafosse@gmail.com
baseurl: "/blog"
url: "http://koluskomtu.github.io"
=======
baseurl: "/blog"
url: "https://koluskomtu.github.io/"
>>>>>>> deb453ab1354efc8ac57fd33b283f1ae2fff85da
github_username:  Koluskomtu
email: "john.lafosse@gmail.com"
future: true
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-sitemap
   - jekyll-feed

exclude: [ 'README.md' ]



 

